### ISSUE TITLE
what i should do on .usmapping?

### ISSUE THREAD

**Issue by TimmieDevelops** [TheNaeem/Unreal-Mappings-Archive#22]
is this for unreal engine or something else?

**Comment by Cracko298** [comment]
These can be used to Data Mine UE4 Games and will be required to Data Mine UE5 games in the near future.

**Comment by TimmieDevelops** [comment]
Ah, alright, thank you so much for telling me❤️

**Comment by Cracko298** [comment]
Happy to Help.
